# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=200),
        ),
    ]
