# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0003_auto_20161101_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
