# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0004_remove_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
