# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 10:16
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('qna_app', '0014_auto_20180222_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_level', models.IntegerField(default=1)),
            ],
        ),
    ]
