# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0015_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
