# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0016_auto_20180301_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
