# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0020_auto_20180315_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
