# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0021_remove_player_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalproblem', models.IntegerField(default=100)),
            ],
        ),
    ]
